name: Build macOS

on:
  push:
    branches:
      - master
      - main
      - 'Direct-FLAC-&-Resampling'
  pull_request:
    branches:
      - master
      - main
      - 'Direct-FLAC-&-Resampling'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/_reusable-macos-build.yml
    with:
      upload_artifacts: true
